version: "3.9"

services:
  eletrixblog:
    image: python:3.12
    container_name: eletrixblog
    working_dir: /app
    ports:
      - "127.0.0.1:5006:5000"
    volumes:
      - /root/containers/blog/articles:/app/articles
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y git &&
        rm -rf /tmp/blog &&
        git clone https://github.com/eletrixtime/blog.git /tmp/blog &&
        cp -r /tmp/blog/. /app/ &&
        pip install --no-cache-dir -r requirements.txt &&
        gunicorn --bind 0.0.0.0:5000 app:app
      "
    restart: always
